### ISSUE TITLE
Volume control

### ISSUE THREAD

**Issue by leerspace** [icidasset/ongaku-ryoho#6]
I think a volume control would be handy. 

I'm not sure if this is already planned, or if maybe there's an ideological opposition to volume controls ([like Bandcamp](https://bandcamp.com/help/audio_basics)'s answer to "where's the volume control?").

**Comment by icidasset** [comment]
Yup, this is planned. There will be an EQ with volume, low-band, mid-band and high-band controls.

**Comment by icidasset** [comment]
@leerspace Just added this. It's in the tracks view, added a new icon just next to the search. Double click to reset. Let me know if the equalizer makes any sense! 😄 Or if there are any problems with it 😉

**Comment by leerspace** [comment]
@icidasset it makes sense to me and works well! From a UI perspective it seems a bit harder to use than sliders, but that could just be a personal preference.
